name: Publish Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.6.1
    - name: Install dependencies
      run: dotnet restore src/NJsonSchema.CodeGeneration.CSharp/NJsonSchema.CodeGeneration.CSharp.csproj
    - name: Build
      run: dotnet build src/NJsonSchema.CodeGeneration.CSharp/NJsonSchema.CodeGeneration.CSharp.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test src/NJsonSchema.CodeGeneration.CSharp.Tests/NJsonSchema.CodeGeneration.CSharp.Tests.csproj --verbosity normal
    - name: Publish cloud.devlpr.NJsonSchema.CodeGeneration.CSharp
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/NJsonSchema.CodeGeneration.CSharp/NJsonSchema.CodeGeneration.CSharp.csproj
          NUGET_KEY: ${{secrets.NUGETAPIKEY}}
          PACKAGE_NAME: cloud.devlpr.NJsonSchema.CodeGeneration.CSharp